"""empty message

Revision ID: 98576ce2349f
Revises: 
Create Date: 2026-07-01 11:09:03.061428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98576ce2349f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('ID', sa.Integer(), nullable=False),
                    sa.Column('comment_text', sa.String(
                        length=1024), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['user.ID'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['post.ID'], ),
                    sa.PrimaryKeyConstraint('ID')
                    )
    op.create_table('post',
                    sa.Column('ID', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('comment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['comment_id'], ['comment.ID'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.ID'], ),
                    sa.PrimaryKeyConstraint('ID')
                    )
    op.create_table('user',
                    sa.Column('ID', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=18), nullable=False),
                    sa.Column('password', sa.String(
                        length=18), nullable=False),
                    sa.Column('firstname', sa.String(
                        length=18), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=18), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('follower',
                    sa.Column('user_from_id', sa.Integer(), nullable=False),
                    sa.Column('user_to_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_from_id'], ['user.ID'], ),
                    sa.ForeignKeyConstraint(['user_to_id'], ['user.ID'], ),
                    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
                    )
    op.create_table('media',
                    sa.Column('ID', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=18), nullable=False),
                    sa.Column('url', sa.String(length=256), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['post.ID'], ),
                    sa.PrimaryKeyConstraint('ID')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('comment')
    op.drop_table('media')
    op.drop_table('follower')
    # ### end Alembic commands ###
